/**
 * 에러 코드 — development_conventions §5.
 * 비밀 도메인 외부 응답은 모두 `NEWS_ARTICLE_NOT_FOUND` 로 통일됨.
 * 아래 코드는 내부 로그·audit·앱 내부 화면 전용.
 */

export const ERROR_CODES = {
  // AUTH (앱 내부 화면 표시 가능)
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_REVOKED: 'AUTH_REFRESH_REVOKED',
  AUTH_EMAIL_DUPLICATE: 'AUTH_EMAIL_DUPLICATE',

  // SEQUENCE (앱 내부)
  SEQUENCE_INVALID_LENGTH: 'SEQUENCE_INVALID_LENGTH',
  SEQUENCE_VERIFY_REQUIRED: 'SEQUENCE_VERIFY_REQUIRED',
  SEQUENCE_RESET_LINK_EXPIRED: 'SEQUENCE_RESET_LINK_EXPIRED',

  // UNLOCK (내부 audit 전용 — 외부 응답은 위장)
  UNLOCK_TOKEN_EXPIRED: 'UNLOCK_TOKEN_EXPIRED',
  UNLOCK_REVOKED: 'UNLOCK_REVOKED',

  // PAIRING (내부 audit 전용)
  PAIRING_ACTIVE_SLOT_OCCUPIED: 'PAIRING_ACTIVE_SLOT_OCCUPIED',
  PAIRING_NOT_FOUND: 'PAIRING_NOT_FOUND',
  PAIRING_ALREADY_PROCESSED: 'PAIRING_ALREADY_PROCESSED',

  // MESSAGE (내부)
  MESSAGE_PAIR_NOT_PAIRED: 'MESSAGE_PAIR_NOT_PAIRED',
  MESSAGE_BODY_TOO_LARGE: 'MESSAGE_BODY_TOO_LARGE',

  // ATTACHMENT (내부 + 앱 내부 표시 가능)
  ATTACHMENT_MIME_NOT_ALLOWED: 'ATTACHMENT_MIME_NOT_ALLOWED',
  ATTACHMENT_SIZE_EXCEEDED: 'ATTACHMENT_SIZE_EXCEEDED',
  ATTACHMENT_MAGIC_BYTE_MISMATCH: 'ATTACHMENT_MAGIC_BYTE_MISMATCH',

  // IDEMPOTENCY (내부)
  IDEMPOTENCY_KEY_MISSING: 'IDEMPOTENCY_KEY_MISSING',
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',

  // NEWS — 외부 위장 응답 공통
  NEWS_ARTICLE_NOT_FOUND: 'NEWS_ARTICLE_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
