-- ============================================================
-- agentNews v1.0 — PostgreSQL 16 DDL
-- Generated by WA-Arch (Claude Opus 4.7) — PLAN-003-DOC-DDL
-- 1:1 with db_design.md v1.0 (G4 gate)
-- ============================================================

-- ---------------------------------------------------------------------
-- 0. Extensions
-- ---------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------
-- 1. Helper functions (used by triggers below)
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION raise_audit_immutable_error()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'audit_logs is append-only — UPDATE/DELETE not allowed';
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- 2. Tables
-- ============================================================

-- ---------------------------------------------------------------------
-- 2-1. agents
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agents (
  id              bigserial PRIMARY KEY,
  external_id     uuid          NOT NULL DEFAULT gen_random_uuid(),
  email           varchar(255)  NOT NULL,
  password_hash   varchar(72)   NOT NULL,
  nickname        varchar(40)   NOT NULL,
  status          varchar(32)   NOT NULL DEFAULT 'ACTIVE'
                    CHECK (status IN ('ACTIVE','DELETED')),
  created_at      timestamptz   NOT NULL DEFAULT now(),
  updated_at      timestamptz   NOT NULL DEFAULT now(),
  deleted_at      timestamptz,
  CONSTRAINT agents_external_id_uq UNIQUE (external_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_agents_email_active
  ON agents (email)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agents_status
  ON agents (status);

CREATE TRIGGER trg_agents_updated_at
  BEFORE UPDATE ON agents
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 2-2. agent_secret_sequences (1:1 with agents)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_secret_sequences (
  id                    bigserial PRIMARY KEY,
  agent_id              bigint        NOT NULL,
  status                varchar(32)   NOT NULL DEFAULT 'NOT_REGISTERED'
                          CHECK (status IN ('NOT_REGISTERED','REGISTERED','RESET_PENDING')),
  sequence_length       smallint
                          CHECK (sequence_length BETWEEN 4 AND 6),
  hash                  bytea,
  salt                  bytea,
  registered_at         timestamptz,
  reset_requested_at    timestamptz,
  created_at            timestamptz   NOT NULL DEFAULT now(),
  updated_at            timestamptz   NOT NULL DEFAULT now(),
  deleted_at            timestamptz,
  CONSTRAINT agent_secret_sequences_agent_fk
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
  CONSTRAINT agent_secret_sequences_registered_check
    CHECK (
      status = 'NOT_REGISTERED'
      OR (hash IS NOT NULL AND salt IS NOT NULL AND sequence_length IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_secret_sequences_agent_active
  ON agent_secret_sequences (agent_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_secret_sequences_status
  ON agent_secret_sequences (status);

CREATE TRIGGER trg_secret_sequences_updated_at
  BEFORE UPDATE ON agent_secret_sequences
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 2-3. sequence_reset_tokens
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sequence_reset_tokens (
  id            bigserial PRIMARY KEY,
  agent_id      bigint        NOT NULL,
  token_hash    bytea         NOT NULL,
  expires_at    timestamptz   NOT NULL,
  consumed_at   timestamptz,
  created_at    timestamptz   NOT NULL DEFAULT now(),
  updated_at    timestamptz   NOT NULL DEFAULT now(),
  CONSTRAINT sequence_reset_tokens_agent_fk
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
  CONSTRAINT sequence_reset_tokens_token_hash_uq UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS idx_reset_tokens_agent
  ON sequence_reset_tokens (agent_id);

CREATE INDEX IF NOT EXISTS idx_reset_tokens_expires
  ON sequence_reset_tokens (expires_at);

CREATE TRIGGER trg_reset_tokens_updated_at
  BEFORE UPDATE ON sequence_reset_tokens
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 2-4. unlock_sessions
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS unlock_sessions (
  id                bigserial PRIMARY KEY,
  agent_id          bigint        NOT NULL,
  token_jti         uuid          NOT NULL DEFAULT gen_random_uuid(),
  status            varchar(32)   NOT NULL DEFAULT 'ACTIVE'
                      CHECK (status IN ('ACTIVE','EXPIRED','REVOKED')),
  issued_at         timestamptz   NOT NULL DEFAULT now(),
  expires_at        timestamptz   NOT NULL,
  last_seen_at      timestamptz   NOT NULL DEFAULT now(),
  revoked_reason    varchar(32)
                      CHECK (revoked_reason IN ('BACKGROUND','LOGOUT','APP_RESTART','PAIR_DISCONNECT','NEW_UNLOCK')),
  created_at        timestamptz   NOT NULL DEFAULT now(),
  updated_at        timestamptz   NOT NULL DEFAULT now(),
  deleted_at        timestamptz,
  CONSTRAINT unlock_sessions_agent_fk
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
  CONSTRAINT unlock_sessions_token_jti_uq UNIQUE (token_jti)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_unlock_active_one_per_agent
  ON unlock_sessions (agent_id)
  WHERE status = 'ACTIVE';

CREATE INDEX IF NOT EXISTS idx_unlock_expires
  ON unlock_sessions (expires_at);

CREATE TRIGGER trg_unlock_sessions_updated_at
  BEFORE UPDATE ON unlock_sessions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 2-5. refresh_tokens
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS refresh_tokens (
  id              bigserial PRIMARY KEY,
  agent_id        bigint        NOT NULL,
  token_jti       uuid          NOT NULL DEFAULT gen_random_uuid(),
  device_label    varchar(120),
  issued_at       timestamptz   NOT NULL DEFAULT now(),
  expires_at      timestamptz   NOT NULL,
  revoked_at      timestamptz,
  created_at      timestamptz   NOT NULL DEFAULT now(),
  updated_at      timestamptz   NOT NULL DEFAULT now(),
  CONSTRAINT refresh_tokens_agent_fk
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
  CONSTRAINT refresh_tokens_token_jti_uq UNIQUE (token_jti)
);

CREATE INDEX IF NOT EXISTS idx_refresh_agent
  ON refresh_tokens (agent_id);

CREATE INDEX IF NOT EXISTS idx_refresh_expires
  ON refresh_tokens (expires_at);

CREATE TRIGGER trg_refresh_tokens_updated_at
  BEFORE UPDATE ON refresh_tokens
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 2-6. push_tokens
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS push_tokens (
  id            bigserial PRIMARY KEY,
  agent_id      bigint        NOT NULL,
  fcm_token     varchar(512)  NOT NULL,
  platform      varchar(16)   NOT NULL
                  CHECK (platform IN ('ios','android')),
  last_seen_at  timestamptz   NOT NULL DEFAULT now(),
  created_at    timestamptz   NOT NULL DEFAULT now(),
  updated_at    timestamptz   NOT NULL DEFAULT now(),
  deleted_at    timestamptz,
  CONSTRAINT push_tokens_agent_fk
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_push_tokens_fcm_active
  ON push_tokens (fcm_token)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_push_tokens_agent_active
  ON push_tokens (agent_id)
  WHERE deleted_at IS NULL;

CREATE TRIGGER trg_push_tokens_updated_at
  BEFORE UPDATE ON push_tokens
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 2-7. pairings
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pairings (
  id                    bigserial PRIMARY KEY,
  external_id           uuid          NOT NULL DEFAULT gen_random_uuid(),
  requester_agent_id    bigint        NOT NULL,
  recipient_agent_id    bigint        NOT NULL,
  status                varchar(32)   NOT NULL DEFAULT 'PAIRING_REQUESTED'
                          CHECK (status IN ('PAIRING_REQUESTED','PAIRED','PAIRING_REJECTED','DISCONNECTED')),
  requested_at          timestamptz   NOT NULL DEFAULT now(),
  accepted_at           timestamptz,
  ended_at              timestamptz,
  ended_by_agent_id     bigint,
  created_at            timestamptz   NOT NULL DEFAULT now(),
  updated_at            timestamptz   NOT NULL DEFAULT now(),
  deleted_at            timestamptz,
  CONSTRAINT pairings_external_id_uq UNIQUE (external_id),
  CONSTRAINT pairings_requester_fk
    FOREIGN KEY (requester_agent_id) REFERENCES agents(id) ON DELETE RESTRICT,
  CONSTRAINT pairings_recipient_fk
    FOREIGN KEY (recipient_agent_id) REFERENCES agents(id) ON DELETE RESTRICT,
  CONSTRAINT pairings_ended_by_fk
    FOREIGN KEY (ended_by_agent_id) REFERENCES agents(id) ON DELETE SET NULL,
  CONSTRAINT pairings_different_agents_chk
    CHECK (requester_agent_id <> recipient_agent_id)
);

-- 1 active pair per agent (REQ-014). 양방향 차단.
CREATE UNIQUE INDEX IF NOT EXISTS idx_pairings_active_requester
  ON pairings (requester_agent_id)
  WHERE status IN ('PAIRING_REQUESTED','PAIRED') AND deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_pairings_active_recipient
  ON pairings (recipient_agent_id)
  WHERE status IN ('PAIRING_REQUESTED','PAIRED') AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_pairings_status_requester
  ON pairings (status, requester_agent_id);

CREATE INDEX IF NOT EXISTS idx_pairings_status_recipient
  ON pairings (status, recipient_agent_id);

CREATE TRIGGER trg_pairings_updated_at
  BEFORE UPDATE ON pairings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 2-8. messages
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS messages (
  id                bigserial PRIMARY KEY,
  external_id       uuid          NOT NULL DEFAULT gen_random_uuid(),
  pairing_id        bigint        NOT NULL,
  sender_agent_id   bigint        NOT NULL,
  status            varchar(32)   NOT NULL DEFAULT 'SENT'
                      CHECK (status IN ('SENT','DELETED')),
  ciphertext        bytea         NOT NULL,
  iv                bytea         NOT NULL CHECK (octet_length(iv) = 12),
  tag               bytea         NOT NULL CHECK (octet_length(tag) = 16),
  has_attachment    boolean       NOT NULL DEFAULT false,
  sent_at           timestamptz   NOT NULL DEFAULT now(),
  created_at        timestamptz   NOT NULL DEFAULT now(),
  updated_at        timestamptz   NOT NULL DEFAULT now(),
  deleted_at        timestamptz,
  CONSTRAINT messages_external_id_uq UNIQUE (external_id),
  CONSTRAINT messages_pairing_fk
    FOREIGN KEY (pairing_id) REFERENCES pairings(id) ON DELETE RESTRICT,
  CONSTRAINT messages_sender_fk
    FOREIGN KEY (sender_agent_id) REFERENCES agents(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_messages_pairing_sent
  ON messages (pairing_id, sent_at DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_messages_sender
  ON messages (sender_agent_id, sent_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_retention
  ON messages (sent_at)
  WHERE deleted_at IS NULL;

CREATE TRIGGER trg_messages_updated_at
  BEFORE UPDATE ON messages
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 2-9. message_attachments
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS message_attachments (
  id                      bigserial PRIMARY KEY,
  external_id             uuid          NOT NULL DEFAULT gen_random_uuid(),
  message_id              bigint,
  uploader_agent_id       bigint        NOT NULL,
  status                  varchar(32)   NOT NULL DEFAULT 'PENDING'
                            CHECK (status IN ('PENDING','AVAILABLE','DELETED')),
  storage_key             varchar(255)  NOT NULL,
  mime_type               varchar(64)   NOT NULL
                            CHECK (mime_type IN ('image/jpeg','image/png','image/webp','application/pdf')),
  file_size_bytes         bigint        NOT NULL
                            CHECK (file_size_bytes > 0 AND file_size_bytes <= 26214400),
  original_filename       varchar(255),
  magic_byte_verified     boolean       NOT NULL DEFAULT false,
  uploaded_at             timestamptz,
  created_at              timestamptz   NOT NULL DEFAULT now(),
  updated_at              timestamptz   NOT NULL DEFAULT now(),
  deleted_at              timestamptz,
  CONSTRAINT message_attachments_external_id_uq UNIQUE (external_id),
  CONSTRAINT message_attachments_storage_key_uq UNIQUE (storage_key),
  CONSTRAINT message_attachments_message_fk
    FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE RESTRICT,
  CONSTRAINT message_attachments_uploader_fk
    FOREIGN KEY (uploader_agent_id) REFERENCES agents(id) ON DELETE RESTRICT,
  -- DESIGN-001: PENDING 단계는 message_id NULL 허용, 그 외는 NOT NULL
  CONSTRAINT message_attachments_message_required_chk
    CHECK (status = 'PENDING' OR message_id IS NOT NULL),
  -- AVAILABLE 진입 조건: 매직바이트 검증 필수
  CONSTRAINT message_attachments_available_verified_chk
    CHECK ((status = 'AVAILABLE') = magic_byte_verified),
  -- image MIME 은 10MB 이내
  CONSTRAINT message_attachments_image_size_chk
    CHECK (
      mime_type = 'application/pdf'
      OR file_size_bytes <= 10485760
    )
);

CREATE INDEX IF NOT EXISTS idx_attachments_message_active
  ON message_attachments (message_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_attachments_uploader
  ON message_attachments (uploader_agent_id);

CREATE INDEX IF NOT EXISTS idx_attachments_status_retention
  ON message_attachments (status, created_at);

CREATE TRIGGER trg_message_attachments_updated_at
  BEFORE UPDATE ON message_attachments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 2-10. fake_headlines  (created before notification_queue: FK target)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fake_headlines (
  id           bigserial PRIMARY KEY,
  headline     varchar(160) NOT NULL,
  category     varchar(32)  NOT NULL DEFAULT 'general'
                 CHECK (category IN ('general','politics','economy','tech','culture')),
  is_active    boolean      NOT NULL DEFAULT true,
  created_at   timestamptz  NOT NULL DEFAULT now(),
  updated_at   timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT fake_headlines_headline_uq UNIQUE (headline)
);

CREATE INDEX IF NOT EXISTS idx_fake_headlines_active
  ON fake_headlines (is_active)
  WHERE is_active = true;

CREATE TRIGGER trg_fake_headlines_updated_at
  BEFORE UPDATE ON fake_headlines
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 2-11. notification_queue
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notification_queue (
  id                      bigserial PRIMARY KEY,
  external_id             uuid         NOT NULL DEFAULT gen_random_uuid(),
  recipient_agent_id      bigint       NOT NULL,
  trigger_kind            varchar(32)  NOT NULL
                            CHECK (trigger_kind IN ('MESSAGE_TEXT','MESSAGE_IMAGE','MESSAGE_FILE','PAIRING_REQUEST','PAIRING_REJECT')),
  trigger_message_id      bigint,
  trigger_pairing_id      bigint,
  fake_headline_id        bigint       NOT NULL,
  status                  varchar(32)  NOT NULL DEFAULT 'QUEUED'
                            CHECK (status IN ('QUEUED','SENT','FAILED')),
  scheduled_at            timestamptz  NOT NULL,
  sent_at                 timestamptz,
  failed_reason           varchar(64),
  created_at              timestamptz  NOT NULL DEFAULT now(),
  updated_at              timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT notification_queue_external_id_uq UNIQUE (external_id),
  CONSTRAINT notification_queue_recipient_fk
    FOREIGN KEY (recipient_agent_id) REFERENCES agents(id) ON DELETE CASCADE,
  CONSTRAINT notification_queue_message_fk
    FOREIGN KEY (trigger_message_id) REFERENCES messages(id) ON DELETE SET NULL,
  CONSTRAINT notification_queue_pairing_fk
    FOREIGN KEY (trigger_pairing_id) REFERENCES pairings(id) ON DELETE SET NULL,
  CONSTRAINT notification_queue_headline_fk
    FOREIGN KEY (fake_headline_id) REFERENCES fake_headlines(id) ON DELETE RESTRICT,
  CONSTRAINT notification_queue_message_trigger_chk
    CHECK (
      (trigger_kind LIKE 'MESSAGE\_%' AND trigger_message_id IS NOT NULL)
      OR (trigger_kind NOT LIKE 'MESSAGE\_%' AND trigger_message_id IS NULL)
    ),
  CONSTRAINT notification_queue_pairing_trigger_chk
    CHECK (
      (trigger_kind LIKE 'PAIRING\_%' AND trigger_pairing_id IS NOT NULL)
      OR (trigger_kind NOT LIKE 'PAIRING\_%' AND trigger_pairing_id IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_notif_queued_scheduled
  ON notification_queue (status, scheduled_at)
  WHERE status = 'QUEUED';

CREATE INDEX IF NOT EXISTS idx_notif_recipient
  ON notification_queue (recipient_agent_id);

CREATE TRIGGER trg_notification_queue_updated_at
  BEFORE UPDATE ON notification_queue
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 2-12. news_articles_cache
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS news_articles_cache (
  id              bigserial PRIMARY KEY,
  batch_id        uuid          NOT NULL DEFAULT gen_random_uuid(),
  display_order   smallint      NOT NULL CHECK (display_order >= 1),
  title           varchar(300)  NOT NULL,
  url             varchar(2048) NOT NULL,
  thumbnail_url   varchar(2048),
  summary         text,
  source          varchar(120),
  published_at    timestamptz,
  fetched_at      timestamptz   NOT NULL DEFAULT now(),
  created_at      timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_news_batch_order
  ON news_articles_cache (batch_id, display_order);

CREATE INDEX IF NOT EXISTS idx_news_fetched
  ON news_articles_cache (fetched_at);

-- ---------------------------------------------------------------------
-- 2-13. audit_logs  (append-only)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
  id                    bigserial PRIMARY KEY,
  occurred_at           timestamptz  NOT NULL DEFAULT now(),
  kind                  varchar(48)  NOT NULL
                          CHECK (kind IN (
                            'USER_SIGNUP','USER_DELETE',
                            'LOGIN_SUCCESS','LOGIN_FAIL',
                            'SEQUENCE_REGISTER','SEQUENCE_CHANGE',
                            'SEQUENCE_RESET_REQUEST','SEQUENCE_RESET_COMPLETE',
                            'UNLOCK_SUCCESS','UNLOCK_FAIL',
                            'UNLOCK_BACKGROUND','UNLOCK_REVOKE',
                            'PAIRING_REQUEST','PAIRING_ACCEPT','PAIRING_REJECT',
                            'PAIRING_CANCEL','PAIRING_DISCONNECT',
                            'MESSAGE_SEND','MESSAGE_DELETE',
                            'ATTACHMENT_UPLOAD_START','ATTACHMENT_AVAILABLE','ATTACHMENT_DELETE',
                            'NOTIFICATION_FAIL'
                          )),
  actor_agent_id        bigint,
  actor_kind            varchar(16)  NOT NULL DEFAULT 'agent'
                          CHECK (actor_kind IN ('agent','system','external')),
  target_type           varchar(32),
  target_id             bigint,
  target_external_id    uuid,
  ip_address            inet,
  user_agent            varchar(255),
  context               jsonb,
  created_at            timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_actor_fk
    FOREIGN KEY (actor_agent_id) REFERENCES agents(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_occurred
  ON audit_logs (occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_actor
  ON audit_logs (actor_agent_id)
  WHERE actor_agent_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_audit_kind
  ON audit_logs (kind);

CREATE INDEX IF NOT EXISTS idx_audit_target
  ON audit_logs (target_type, target_id);

-- Append-only trigger (SEC-010, REQ-025)
CREATE TRIGGER trg_audit_logs_immutable
  BEFORE UPDATE OR DELETE ON audit_logs
  FOR EACH ROW EXECUTE FUNCTION raise_audit_immutable_error();

-- ---------------------------------------------------------------------
-- 2-14. idempotency_keys
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS idempotency_keys (
  id                bigserial PRIMARY KEY,
  agent_id          bigint        NOT NULL,
  key_value         varchar(255)  NOT NULL,
  request_hash      bytea         NOT NULL,
  response_status   smallint,
  response_body     jsonb,
  created_at        timestamptz   NOT NULL DEFAULT now(),
  expires_at        timestamptz   NOT NULL,
  CONSTRAINT idempotency_keys_agent_fk
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
  CONSTRAINT idempotency_keys_agent_key_uq UNIQUE (agent_id, key_value)
);

CREATE INDEX IF NOT EXISTS idx_idempotency_expires
  ON idempotency_keys (expires_at);

-- ============================================================
-- 3. End of schema
-- ============================================================

-- Total: 14 tables + pgcrypto extension + 2 helper functions + audit immutability trigger
-- + per-table updated_at triggers (12 tables — audit_logs / news_articles_cache / idempotency_keys 제외)
-- Status values mapped (G4): agents.status, agent_secret_sequences.status, unlock_sessions.status,
-- pairings.status, messages.status, message_attachments.status, notification_queue.status — 21/21
